name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install LibXML2
        run: |
          sudo apt update
          sudo apt-get install libxml2-utils

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependencies
        run: |
          pip install python-coveralls
          pip install nose
          pip install -I coverage
          pip install .

      - name: Run tests
        run: |
          nosetests --with-coverage
